# Generated by Django 3.2 on 2022-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_contrato', models.CharField(max_length=30)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('nombre_de_la_empresa', models.CharField(max_length=70)),
                ('fecha', models.DateField()),
                ('contenido_del_contrato', models.CharField(max_length=3000)),
            ],
        ),
    ]
