# Generated by Django 3.2 on 2022-09-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='nombre_empresa',
        ),
    ]
