# Generated by Django 3.2 on 2022-09-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_pdf', '0003_alter_contratos_contenido_del_contrato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contratos',
            new_name='Contrato',
        ),
    ]
