# Generated by Django 3.2 on 2022-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_pdf', '0004_rename_contratos_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='image',
            field=models.ImageField(null=True, upload_to='contrato'),
        ),
    ]
