# Generated by Django 3.2 on 2022-09-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_pdf', '0005_contrato_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_de_la_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos_pdf.empresa'),
        ),
    ]
