# Generated by Django 3.2 on 2022-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_pdf', '0006_auto_20220909_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nombre_de_la_empresa',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
